#ifndef CONSTANTS_H_IN
#define CONSTANTS_H_IN

// Unicode
#define B_PAWN_UCS 0x2659
#define B_ROOK_UCS 0x2656
#define B_KNIGHT_UCS 0x2658
#define B_BISHOP_UCS 0x2657
#define B_QUEEN_UCS 0x2655
#define B_KING_UCS 0x2654

#define W_PAWN_UCS 0x265F
#define W_ROOK_UCS 0x265C
#define W_KNIGHT_UCS 0x265E
#define W_BISHOP_UCS 0x265D
#define W_QUEEN_UCS 0x265B
#define W_KING_UCS 0x265A

// Squares
#define SQUARE_HEIGHT 3
#define SQUARE_WIDTH 7
#define W_SQUARE_FG COLOR_BLUE
#define W_SQUARE_BG COLOR_BLUE
#define B_SQUARE_FG COLOR_RED
#define B_SQUARE_BG COLOR_RED
#define W_SQUARE_COLOR 136
#define B_SQUARE_COLOR 137

// Board
#define BOARD_BORDER_HEIGHT ( SQUARE_HEIGHT / 2 )
#define BOARD_BORDER_WIDTH ( SQUARE_WIDTH / 2 - 1 )
#define BOARD_NO_BORDER_HEIGHT ( SQUARE_HEIGHT * 8 )
#define BOARD_NO_BORDER_WIDTH ( SQUARE_WIDTH * 8 )
#define BOARD_HEIGHT BOARD_NO_BORDER_HEIGHT + 2 * BOARD_BORDER_HEIGHT
#define BOARD_WIDTH BOARD_NO_BORDER_WIDTH + 2 * BOARD_BORDER_WIDTH

#endif // CONSTANTS_H_IN
